const MINUTES_PER_HOUR = 60;
const formatTime = (minutes: number) =>
  `${String(Math.floor(minutes / MINUTES_PER_HOUR)).padStart(2, '0')}:${String(
    minutes % MINUTES_PER_HOUR,
  ).padStart(2, '0')}`;

export const BOOKING_TIME_STEP_MINUTES = 15;
export const BOOKING_MIN_DURATION_MINUTES = BOOKING_TIME_STEP_MINUTES;
export const BOOKING_DEFAULT_DURATION_MINUTES = MINUTES_PER_HOUR;
export const BOOKING_MAX_ADVANCE_DAYS = 30;
export const BOOKING_MAX_ADVANCE_MS =
  BOOKING_MAX_ADVANCE_DAYS * 24 * MINUTES_PER_HOUR * MINUTES_PER_HOUR * 1000;
export const BOOKING_WORKDAY_START_MINUTES = 9 * MINUTES_PER_HOUR;
export const BOOKING_WORKDAY_END_MINUTES = 20 * MINUTES_PER_HOUR;
export const BOOKING_WORKDAY_DURATION_MINUTES =
  BOOKING_WORKDAY_END_MINUTES - BOOKING_WORKDAY_START_MINUTES;
export const BOOKING_WORKDAY_START = formatTime(BOOKING_WORKDAY_START_MINUTES);
export const BOOKING_WORKDAY_END = formatTime(BOOKING_WORKDAY_END_MINUTES);
export const BOOKING_LATEST_START = formatTime(
  BOOKING_WORKDAY_END_MINUTES - BOOKING_TIME_STEP_MINUTES,
);
export const BOOKING_TITLE_MAX_LENGTH = 200;
export const BOOKING_COMMENT_MAX_LENGTH = 2_000;
export const BOOKING_RECURRENCE_INTERVAL_DAYS = 7;
export const BOOKING_MIN_RECURRENCE_COUNT = 2;
export const BOOKING_MAX_RECURRENCE_COUNT = 5;
